### ISSUE TITLE
Fleets: Export for all Ships

### ISSUE THREAD

**Issue by mortik** [fleetyards/api#2053]

**Comment by Dave247** [comment]
If possible to also have an option to export it as the total number of all ships combined (including duplicates), and only individual unique ships as currently doing it directly through the site only allows for the latter and not the former.

**Comment by mortik** [comment]
If you only need a json export you can already get all ships via the grouped query parameter

```https://api.fleetyards.net/v1/fleets/*fleet-id*/vehicles?perPage=all&grouped=false```

**Comment by Dave247** [comment]
Unfortunately the output doesn't seem to be readable on the Starship42 site, at least in its raw form as I'm noticing it contains a lot of extra and unnecessary junk data that isn't included from on export on either site and/or is missing required data it needs to load the list.

**Comment by mortik** [comment]
Oh, you need it to import it to starship42. Yes, the API JSON is incompatible with starship42. I will keep compatibility with starship42 in mind once I start implementing the fleet export feature.

**Comment by mortik** [comment]
This has been resolved with #2516
