### ISSUE TITLE
What about all ships options ?

### ISSUE THREAD

**Issue by NargiT** [fleetyards/api#2555]
Would be nice to have a "all ship" options for membership settings.

![image](https://user-images.githubusercontent.com/3153333/220134082-d10224f2-857f-417c-819d-378093e3abf9.png)

**Comment by mortik** [comment]
This will be resolved once #2559 is released to Live

**Comment by NargiT** [comment]
@mortik do you publish a deployment notification on discord when it's live ?
I guess we can close it then ?

**Comment by mortik** [comment]
yes
