### ISSUE TITLE
Refactor purchase functionnality

### ISSUE THREAD

**Issue by NargiT** [fleetyards/api#2556]
![image](https://user-images.githubusercontent.com/3153333/220134973-86a12128-96be-4ee5-93e4-41106e1b2678.png)

A lot of people think "purchased" means "ship was bought with real money". As a matter of fact it simply means "have in game".

I believe the logic needs to be reversed or wording needs to be changed. But fleetyard by default act more as a wish list than an actual fleet. Some people are also confused with the buy back. Thus I believe something can be done at the UX level to help users.

**Comment by mortik** [comment]
Related to #1968

**Comment by mortik** [comment]
Was resolved by #2559
