### ISSUE TITLE
Api Schema: Fleets

### ISSUE THREAD

**Issue by mortik** [fleetyards/api#2647]
- [x] fleet endpoints 08a3be04809a9a4b16b47709895f4df4324eee8f
- [x] fleet vehicles endpoints aa931ed4b91b614c6e01aa62efc314a05d446555
- [x] fleet members/membership endpoints c840e916f47afa2ae9bc783fed7aa4f281ee906d
- [x] fleet stats endpoints aa931ed4b91b614c6e01aa62efc314a05d446555
- [x] fleet invite-urls endpoints e292fbaa0986c2b277c88e969ed06a1e9c2074b3

**Comment by NargiT** [comment]
Very excited by this feature

**Comment by mortik** [comment]
Released to Live

**Comment by NargiT** [comment]
WOOOOOOOOOOOOOOOOOW !!!! 🎉 🎉 🎉 🎉 🎉 🎉
